# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ms_stt/protos/stt.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ms_stt/protos/stt.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ms_stt/protos/stt.proto\x12\x06ms_stt\"\x85\x01\n\nSTTRequest\x12#\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x11.ms_stt.STTConfigH\x00\x12#\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.ms_stt.AudioChunkH\x00\x12\"\n\x03\x65nd\x18\x03 \x01(\x0b\x32\x13.ms_stt.EndOfStreamH\x00\x42\t\n\x07payload\"[\n\tSTTConfig\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0esample_rate_hz\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x10\n\x08\x65ncoding\x18\x04 \x01(\t\"\x1b\n\nAudioChunk\x12\r\n\x05\x61udio\x18\x01 \x01(\x0c\"\r\n\x0b\x45ndOfStream\"d\n\x0bSTTResponse\x12(\n\x05\x66inal\x18\x01 \x01(\x0b\x32\x17.ms_stt.FinalTranscriptH\x00\x12!\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.ms_stt.STTErrorH\x00\x42\x08\n\x06result\"3\n\x0f\x46inalTranscript\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\")\n\x08STTError\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x32O\n\x0cSpeechToText\x12?\n\x10StreamTranscribe\x12\x12.ms_stt.STTRequest\x1a\x13.ms_stt.STTResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ms_stt.protos.stt_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STTREQUEST']._serialized_start=36
  _globals['_STTREQUEST']._serialized_end=169
  _globals['_STTCONFIG']._serialized_start=171
  _globals['_STTCONFIG']._serialized_end=262
  _globals['_AUDIOCHUNK']._serialized_start=264
  _globals['_AUDIOCHUNK']._serialized_end=291
  _globals['_ENDOFSTREAM']._serialized_start=293
  _globals['_ENDOFSTREAM']._serialized_end=306
  _globals['_STTRESPONSE']._serialized_start=308
  _globals['_STTRESPONSE']._serialized_end=408
  _globals['_FINALTRANSCRIPT']._serialized_start=410
  _globals['_FINALTRANSCRIPT']._serialized_end=461
  _globals['_STTERROR']._serialized_start=463
  _globals['_STTERROR']._serialized_end=504
  _globals['_SPEECHTOTEXT']._serialized_start=506
  _globals['_SPEECHTOTEXT']._serialized_end=585
# @@protoc_insertion_point(module_scope)
